FIX Add protection against deprecated warning from `mb_check_encoding()`
silverstripe/silverstripe-restfulserver pull request #136
Opened 2024-10-14 22:58 UTC by edwilde

## Description

When the `$fieldValue` is not set, the `mb_check_encoding()` function raises a deprecation warning.

```
[Deprecated] mb_check_encoding(): Calling mb_check_encoding() without argument is deprecated
```

So we make sure the field value is set before using it.

## Manual testing steps

Use the restful server to output a field which is not set

## Issues

- #123 

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-10-22 05:00 UTC, emteknetnz requested changes
Please target 3.0 so that it can be patched released. You may need to rebase after doing that

2024-10-22 19:39 UTC, edwilde commented
All set 🚀 

...also noticed that CI is not testing in PHP 8.3, that expected?

2024-10-23 02:43 UTC, emteknetnz commented
Hmm strange it's not testing in PHP 8.3 on pull-requests. It is testing 8.3 on the regular CI build, so on the very low chance there is an issue it'll be picked up within the next week or so.

2024-10-23 02:45 UTC, emteknetnz approved these changes

2024-10-23 02:46 UTC, merged

2024-10-23 02:46 UTC, emteknetnz commented
Linked PR has been merged, it will be automatically released shortly